name: basicrag
channels:
  - conda-forge
  - bioconda
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py312he52fbff_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - altair=6.0.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anthropic=0.75.0=pyhd8ed1ab_0
  - anyio=4.12.0=pyhcf101f3_0
  - asgiref=3.11.0=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h1ddaa69_0
  - aws-c-cal=0.9.13=h6ee9776_1
  - aws-c-common=0.12.6=hc919400_0
  - aws-c-compression=0.3.1=h16f91aa_9
  - aws-c-event-stream=0.5.7=h9ae9c55_1
  - aws-c-http=0.10.7=h5928ca5_5
  - aws-c-io=0.23.3=hbe03c90_5
  - aws-c-mqtt=0.13.3=haf5c5c8_11
  - aws-c-s3=0.11.3=h8da9771_1
  - aws-c-sdkutils=0.2.4=h16f91aa_4
  - aws-checksums=0.2.7=h16f91aa_5
  - aws-crt-cpp=0.35.4=h74951b9_0
  - aws-sdk-cpp=1.11.606=h4e1b0f7_10
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h7e4aa5d_1
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - backoff=2.2.1=pyhd8ed1ab_1
  - backports.zstd=1.3.0=py312h44dc372_0
  - bcrypt=5.0.0=py312h6ef9ec0_1
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py312h0dfefe5_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.4=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312h1b4d9a2_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - chromadb=1.2.1=py312h72bad05_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - cpython=3.12.12=py312hd8ed1ab_1
  - cryptography=46.0.3=py312hd13a024_1
  - dataclasses=0.8=pyhc8e2a94_3
  - deprecated=1.3.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - dnspython=2.8.0=pyhcf101f3_0
  - docstring_parser=0.17.0=pyhd8ed1ab_0
  - durationpy=0.10=pyhd8ed1ab_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fastapi=0.115.9=pyh29332c3_0
  - fastapi-cli=0.0.20=pyhcf101f3_0
  - filelock=3.20.1=pyhd8ed1ab_0
  - frozenlist=1.7.0=py312h512c567_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py312hee6aa52_2
  - google-auth=2.45.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - grpcio=1.73.1=py312h9bc1d27_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.1=py310h6ce4931_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py312h4409184_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=1.2.3=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h38cb7af_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jiter=0.12.0=py312h7a0e18e_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=22.0.0=he6e817a_6_cpu
  - libarrow-acero=22.0.0=hc317990_6_cpu
  - libarrow-compute=22.0.0=h75845d1_6_cpu
  - libarrow-dataset=22.0.0=hc317990_6_cpu
  - libarrow-substrait=22.0.0=h144af7f_6_cpu
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=21.1.8=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=22.0.0=h0ac143b_6_cpu
  - libpng=1.6.53=hfab5511_0
  - libprotobuf=6.31.1=h98f38fd_4
  - libpulsar=4.0.0=h467ef97_0
  - libre2-11=2025.11.05=h91c62da_0
  - libsqlite=3.51.1=h1b79a29_1
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libutf8proc=2.11.2=hd2415e0_0
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h8d039ee_1
  - libxml2-16=2.15.1=h5ef1a60_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h5748b74_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mmh3=5.2.0=py312h455b684_2
  - monotonic=1.6=pyhd8ed1ab_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.7.0=py312hf0dca4a_0
  - narwhals=2.14.0=pyhcf101f3_0
  - ncurses=6.5=h5e97a16_3
  - nlohmann_json=3.12.0=h248ca61_1
  - numpy=2.4.0=py312he281c53_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - onnxruntime=1.22.2=py312h4d4766a_1_cpu
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - opentelemetry-api=1.39.1=pyhd8ed1ab_0
  - opentelemetry-exporter-otlp-proto-common=1.39.1=pyhd8ed1ab_0
  - opentelemetry-exporter-otlp-proto-grpc=1.39.1=pyhd8ed1ab_0
  - opentelemetry-instrumentation=0.60b1=pyhd8ed1ab_0
  - opentelemetry-instrumentation-asgi=0.60b1=pyhd8ed1ab_0
  - opentelemetry-instrumentation-fastapi=0.60b1=pyhd8ed1ab_0
  - opentelemetry-proto=1.39.1=pyhd8ed1ab_0
  - opentelemetry-sdk=1.39.1=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.60b1=pyhd8ed1ab_0
  - opentelemetry-util-http=0.60b1=pyhd8ed1ab_0
  - orc=2.2.1=h4fd0076_0
  - orjson=3.11.5=py312h6f167cc_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312h5978115_2
  - pillow=12.0.0=py312h95c711c_2
  - pip=25.3=pyh8b19718_0
  - posthog=5.4.0=pyhd8ed1ab_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - propcache=0.3.1=py312h998013c_0
  - protobuf=6.31.1=py312h2c926ec_2
  - pthread-stubs=0.4=hd74edd7_1002
  - pulsar-client=3.8.0=py312ha28e04c_3
  - pyarrow=22.0.0=py312h1f38498_0
  - pyarrow-core=22.0.0=py312hea229ce_0_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybase64=1.4.3=py312h4409184_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py312h6ef9ec0_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pypdf2=3.0.1=pyhd8ed1ab_1
  - pypika=0.48.9=pyhd8ed1ab_1
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=h18782d2_1_cpython
  - python-build=1.3.0=pyhff2d567_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-flatbuffers=25.9.23=pyh1e1bc0e_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-kubernetes=33.1.0=pyhd8ed1ab_0
  - python-multipart=0.0.21=pyh332efcf_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.3=pyh7db6752_0
  - re2=2025.11.05=h64b956e_0
  - readline=8.3=h46df422_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.17.1=pyhcf101f3_0
  - rpds-py=0.30.0=py312h6ef9ec0_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - starlette=0.45.3=pyha770c72_0
  - streamlit=1.52.2=pyhd8ed1ab_0
  - sympy=1.14.0=pyh2585a3b_105
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_3
  - tokenizers=0.22.2=py312hab2ecbf_0
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.4=py312h4409184_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typer=0.21.0=pyhbb89825_0
  - typer-slim=0.21.0=pyhcf101f3_0
  - typer-slim-standard=0.21.0=hd63da06_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - uvicorn=0.40.0=pyhc90fa1f_0
  - uvicorn-standard=0.40.0=h4cd5af1_0
  - uvloop=0.22.1=py312h4409184_1
  - watchdog=6.0.0=py312h4409184_2
  - watchfiles=1.1.1=py312h7a0e18e_0
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - websockets=15.0.1=py312h290adc7_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py312h163523d_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py312h5748b74_0
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.2=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
prefix: /Users/dripshabh/miniforge3/envs/basicrag
